{
  "hash": "868f3f8f3923e7036ec0a45ed7609290",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"**Bayesian Thinking and Bayes Rule**\"\nsubtitle: \"**STA6349: Applied Bayesian Analysis** <br> Spring 2025\"\ndate-format: long\nexecute:\n  echo: true\n  warning: false\n  message: false\n  error: true\nformat: \n  revealjs:\n    code-overflow: wrap\n    embed-resources: true\n    slide-number: false\n    width: 1600\n    height: 900\n    html-math-method: katex\n    theme:\n      - default\n      - sp25.scss\neditor: source\n---\n\n\n\n## **Thinking Like a Bayesian**  \n\n- Bayesian analysis involves updating beliefs based on observed data.\n\n![](images/W05-L1-a.png){fig-align=\"center\"} \n\n## **Thinking Like a Bayesian**  \n\n- This is the natural Bayesian knowledge-building process of:\n    - acknowledging your preconceptions (prior distribution),\n    - using data (data distribution) to update your knowledge (posterior distribution), and \n    - repeating (posterior distribution $\\to$ new prior distribution)\n\n![](images/W05-L1-b.png){fig-align=\"center\"} \n\n## **Thinking Like a Bayesian**  \n\n- Bayesian and frequentist analyses share a common goal: to learn from data about the world around us. \n    - Both Bayesian and frequentist analyses use data to fit models, make predictions, and evaluate hypotheses. \n    - When working with the same data, they will typically produce a similar set of conclusions. \n    \n- Statisticians typically identify as either a \"Bayesian\" or \"frequentist\" ...\n    - 🚫 We are not going to \"take sides.\" \n    - ✅ We will see these as tools in our toolbox.\n\n## **Thinking Like a Bayesian**  \n    \n- Bayesian probability: the relative plausibility of an event.\n    - Considers prior belief.\n\n![](images/W05-L1-b.png){fig-align=\"center\"}     \n    \n## **Thinking Like a Bayesian**  \n\n- Frequentist probability: the long-run relative frequency of a repeatable event.\n    - Does not consider prior belief.   \n    \n![](images/W05-L1-c.png){fig-align=\"center\"} \n\n## **Thinking Like a Bayesian**  \n\n- The Bayesian framework depends upon prior information, data, and the balance between them.\n\n    - The balance between the prior information and data is determined by the relative strength of each\n\n![](images/W05-L1-d.png){fig-align=\"center\"} \n\n- When we have little data, our posterior can rely more on prior knowledge. \n\n- As we collect more data, the prior can lose its influence.\n\n## **Thinking Like a Bayesian**  \n\n- We can also use this approach to combine analysis results.\n\n![](images/W05-L1-e.png){fig-align=\"center\"} \n\n## **Bayes Rule**  \n\n- We will use an example to work through Bayesian logic.\n\n- The Collins Dictionary named \"fake news\" the 2017 term of the year. \n\n    - Fake, misleading, and biased news has proliferated along with online news and social media platforms which allow users to post articles with little quality control. \n    \n- We want to flag articles as \"real\" or \"fake.\" \n\n- We'll examine a sample of 150 articles which were posted on Facebook and fact checked by five BuzzFeed journalists (Shu et al. 2017). \n\n## **Bayes Rule**  \n\n- Information about each article is stored in the `fake_news` dataset in the `bayesrules` package. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfake_news <- bayesrules::fake_news\nprint(colnames(fake_news))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"title\"                   \"text\"                   \n [3] \"url\"                     \"authors\"                \n [5] \"type\"                    \"title_words\"            \n [7] \"text_words\"              \"title_char\"             \n [9] \"text_char\"               \"title_caps\"             \n[11] \"text_caps\"               \"title_caps_percent\"     \n[13] \"text_caps_percent\"       \"title_excl\"             \n[15] \"text_excl\"               \"title_excl_percent\"     \n[17] \"text_excl_percent\"       \"title_has_excl\"         \n[19] \"anger\"                   \"anticipation\"           \n[21] \"disgust\"                 \"fear\"                   \n[23] \"joy\"                     \"sadness\"                \n[25] \"surprise\"                \"trust\"                  \n[27] \"negative\"                \"positive\"               \n[29] \"text_syllables\"          \"text_syllables_per_word\"\n```\n\n\n:::\n:::\n\n\n\n- We could build a simple news filter which uses the following rule: since most articles are real, we should read and believe all articles. \n    - While this filter would solve the problem of disregarding real articles, we would read lots of fake news. \n    - It also only takes into account the overall rates of, not the typical features of, real and fake news.\n\n## **Thinking Like a Bayesian**  \n\n\n\n::: {.cell}\n\n:::\n\n\n\n- Suppose that the most recent article posted to a social media platform is titled: *The president has a funny secret!*\n    - Some features of this title probably set off some red flags. \n    - For example, the usage of an exclamation point might seem like an odd choice for a real news article. \n\n- In the dataset, what is the split of real and fake articles?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfake_news %>% tabyl(type)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n type  n percent\n fake 60     0.4\n real 90     0.6\n```\n\n\n:::\n:::\n\n\n\n- Our data backs up our instinct on the article, \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfake_news %>% tabyl(title_has_excl, type) %>%\n  adorn_percentages(\"col\") %>%\n  adorn_pct_formatting(digits = 2) %>%\n  adorn_ns()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n title_has_excl        fake        real\n          FALSE 73.33% (44) 97.78% (88)\n           TRUE 26.67% (16)  2.22%  (2)\n```\n\n\n:::\n:::\n\n\n    \n- In this dataset, 26.67% (16 of 60) of fake news titles but only 2.22% (2 of 90) of real news titles use an exclamation point.\n    \n## **Thinking Like a Bayesian**  \n\n- We now have two pieces of contradictory information. \n    - Our prior information suggested that incoming articles are most likely real. \n    - However, the exclamation point data is more consistent with fake news. \n\n![](images/W05-L1-f.png){fig-align=\"center\"} \n\n- Thinking like Bayesians, we know that balancing both pieces of information is important in developing a posterior understanding of whether the article is fake.\n\n## **Building a Bayesian Model**  \n\n- Our fake news analysis studies two variables: \n    - an article's fake vs real status and \n    - its use of exclamation points. \n    \n- We can represent the randomness in these variables using probability models. \n\n- We will now build: \n    - a prior probability model for our prior understanding of whether the most recent article is fake; \n    - a model for interpreting the exclamation point data; and, eventually, \n    - a posterior probability model which summarizes the posterior plausibility that the article is fake.\n\n## **Building a Bayesian Model**  \n\n- Let's now formalize our prior understanding of whether the new article is fake. \n\n- Based on our `fake_news` data, we saw that 40% of articles are fake and 60% are real. \n\n    - Before reading the new article, there’s a 0.4 prior probability that it's fake and a 0.6 prior probability it's not.\n    \n$$P\\left[B\\right] = 0.40 \\text{ and } P\\left[B\\right] = 0.40$$    \n\n- Remember that a valid probability model must: \n\n    1. account for all possible events (all articles must be fake or real); \n    2. it assigns prior probabilities to each event; and \n    3. the probabilities sum to one.\n    \n## **Building a Bayesian Model**  \n    \n- Now we will summarize the insights from the data we collected on the new article.\n    - We want to formalize our observation that the exclamation point data is more compatible with fake news than with real news. \n    \n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ggexqtqvxa\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ggexqtqvxa table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ggexqtqvxa thead, #ggexqtqvxa tbody, #ggexqtqvxa tfoot, #ggexqtqvxa tr, #ggexqtqvxa td, #ggexqtqvxa th {\n  border-style: none;\n}\n\n#ggexqtqvxa p {\n  margin: 0;\n  padding: 0;\n}\n\n#ggexqtqvxa .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ggexqtqvxa .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ggexqtqvxa .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ggexqtqvxa .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ggexqtqvxa .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ggexqtqvxa .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ggexqtqvxa .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ggexqtqvxa .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ggexqtqvxa .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ggexqtqvxa .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ggexqtqvxa .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ggexqtqvxa .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ggexqtqvxa .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ggexqtqvxa .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ggexqtqvxa .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ggexqtqvxa .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ggexqtqvxa .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ggexqtqvxa .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ggexqtqvxa .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ggexqtqvxa .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ggexqtqvxa .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ggexqtqvxa .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ggexqtqvxa .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ggexqtqvxa .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ggexqtqvxa .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ggexqtqvxa .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ggexqtqvxa .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ggexqtqvxa .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ggexqtqvxa .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ggexqtqvxa .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ggexqtqvxa .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ggexqtqvxa .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ggexqtqvxa .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ggexqtqvxa .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ggexqtqvxa .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ggexqtqvxa .gt_left {\n  text-align: left;\n}\n\n#ggexqtqvxa .gt_center {\n  text-align: center;\n}\n\n#ggexqtqvxa .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ggexqtqvxa .gt_font_normal {\n  font-weight: normal;\n}\n\n#ggexqtqvxa .gt_font_bold {\n  font-weight: bold;\n}\n\n#ggexqtqvxa .gt_font_italic {\n  font-style: italic;\n}\n\n#ggexqtqvxa .gt_super {\n  font-size: 65%;\n}\n\n#ggexqtqvxa .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ggexqtqvxa .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ggexqtqvxa .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ggexqtqvxa .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ggexqtqvxa .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ggexqtqvxa .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ggexqtqvxa .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ggexqtqvxa .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ggexqtqvxa div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"title_has_excl\">title_has_excl</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"fake\">fake</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"real\">real</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"title_has_excl\" class=\"gt_row gt_center\">FALSE</td>\n<td headers=\"fake\" class=\"gt_row gt_right\">73.3% (44)</td>\n<td headers=\"real\" class=\"gt_row gt_right\">97.8% (88)</td></tr>\n    <tr><td headers=\"title_has_excl\" class=\"gt_row gt_center\">TRUE</td>\n<td headers=\"fake\" class=\"gt_row gt_right\">26.7% (16)</td>\n<td headers=\"real\" class=\"gt_row gt_right\">2.2%  (2)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n    \n- We have the following conditional probabilities:\n    - If an article is fake ($B$), then there’s a roughly 26.67% chance it uses exclamation points in the title. \n    - If an article is real ($B^c$), then there’s only a roughly 2.22% chance it uses exclamation points. \n    \n- Looking at the probabilities, we can see that 26.67% of fake articles vs. 2.22% of real articles use exclamation points.\n    - Exclamation point usage is much more likely among fake news than real news.\n    - We have evidence that the article is fake.    \n    \n\n## **Building a Bayesian Model**  \n\n- Note that we know that the incoming article used exclamation points ($A$), but we do not actually know if the article is fake ($B$ or $B^c$).\n\n- In this case, we compared $P[A|B]$ and $P[A|B^c]$ to ascertain the relative likelihood of observing $A$ under different scenarios.\n\n$$L\\left[B|A\\right] = P\\left[A|B\\right] \\text{ and } L\\left[B^c|A\\right] = P\\left[A|B^c\\right]$$\n\n| Event | *B* | *B^c^* | Total |\n|--|:--:|:--:|:--:|\n| Prior Probability | 0.4 | 0.6 | 1.0 |\n| Likelihood | 0.2667 | 0.0222 | 0.2889 |\n\n- It is important for us to note that the likelihood function is *not* a probability function.\n    - This is a framework to compare the relative comparability of our exclamation point data with $B$ and $B^c$.\n\n## **Building a Bayesian Model**  \n\n| Event | *B* (fake) | *B^c^* (real) | Total |\n|--|:--:|:--:|:--:|\n| Prior Probability | 0.4 | 0.6 | 1.0 |\n| Likelihood | 0.2667 | 0.0222 | 0.2889 |\n\n- The prior evidence suggested the article is most likely real,\n\n$$P[B] = 0.4 < P[B^c] = 0.6$$\n\n- The data, however, is more consistent with the article being fake,\n\n$$L[B|A] = 0.2667 > L[B^c|A] = 0.0222$$\n\n## **Building a Bayesian Model**  \n\n- We can summarize our probabilities in a table, but some calculations are required.\n\n- Here's what we know,\n\n|           | $B$ | $B^c$ | Total |\n|-----------|:---:|:-----:|:-----:|\n| $A$       |     |       |       |\n| $A^c$     |     |       |       |\n| **Total** | 0.4 | 0.6   | 1     |\n\n- We also know $P[A|B] = 0.2667$ and $P[A|B^c]=0.0222$.\n\n- Thus,\n\n$$\n\\begin{align*}\nP[A \\cap B] &= P[A|B] \\times P[B] \\\\\n&= 0.2667 \\times 0.4 \\\\\n&= 0.1067\n\\end{align*}\n$$\n\n\n## **Building a Bayesian Model**  \n\n- Here's what we know,\n\n|           | $B$ | $B^c$ | Total |\n|-----------|:---:|:-----:|:-----:|\n| $A$       | 0.1067    |       |       |\n| $A^c$     |     |       |       |\n| **Total** | 0.4 | 0.6   | 1     |\n\n- We also know $P[A|B] = 0.2667$ and $P[A|B^c]=0.0222$.\n\n- Thus,\n\n$$\n\\begin{align*}\nP[A^c \\cap B] &= P(A^c|B) \\times P[B]  \\\\\n&= (1-P[A|B]) \\times P[B] \\\\\n&= (1-0.2667) \\times 0.4 \\\\\n&= 0.2933\n\\end{align*}\n$$\n\n## **Building a Bayesian Model**  \n\n- Here's what we know,\n\n|           | $B$ | $B^c$ | Total |\n|-----------|:---:|:-----:|:-----:|\n| $A$       | 0.1067 |       |       |\n| $A^c$     | 0.2933 |       |       |\n| **Total** | 0.4 | 0.6   | 1     |\n\n- We also know $P[A|B] = 0.2667$ and $P[A|B^c]=0.0222$.\n\n- Thus,\n\n$$\n\\begin{align*}\nP[A \\cap B^c] &= P[A|B^c] \\times P[B^c]  \\\\\n&= 0.0222 \\times 0.6 \\\\\n&= 0.0133\n\\end{align*}\n$$\n\n## **Building a Bayesian Model**  \n\n- Here's what we know,\n\n|           | $B$ | $B^c$ | Total |\n|-----------|:---:|:-----:|:-----:|\n| $A$       | 0.1067 | 0.0133 |       |\n| $A^c$     | 0.2933 |       |       |\n| **Total** | 0.4 | 0.6   | 1     |\n\n- We also know $P[A|B] = 0.2667$ and $P[A|B^c]=0.0222$.\n\n- Thus,\n\n$$\n\\begin{align*}\nP[A^c \\cap B^c] &= P[A^c|B^c] \\times P[B^c]  \\\\\n&= 0.9778 \\times 0.6 \\\\\n&= 0.5867\n\\end{align*}\n$$\n\n## **Building a Bayesian Model**  \n\n- Here's what we know,\n\n|           | $B$ | $B^c$ | Total |\n|-----------|:---:|:-----:|:-----:|\n| $A$       | 0.1067 | 0.0133 |       |\n| $A^c$     | 0.2933 | 0.5867 |       |\n| **Total** | 0.4 | 0.6   | 1     |\n\n- Finally,\n\n$$\n\\begin{align*}\n&P[A] = 0.1067 + 0.0133 = 0.12 \\\\\n&P[A^c] = 0.2933 + 0.5867 = 0.88\n\\end{align*}\n$$\n\n## **Building a Bayesian Model**   \n\n- Using rules of probability, we have completed the table.\n\n|           | $B$ | $B^c$ | Total |\n|-----------|:---:|:-----:|:-----:|\n| $A$       | 0.1067 | 0.0133 | 0.12 |\n| $A^c$     | 0.2933 | 0.5867 | 0.88 |\n| **Total** | 0.4 | 0.6   | 1     |\n\n## **Building a Bayesian Model**   \n\n- With more information, we can answer the question: what is the probability that the latest article is fake?\n\n- We will use the posterior probability, $P[B|A]$, which is found using Bayes' Rule.\n\n- **Bayes' Rule**: For events $A$ and $B$, \n\n$$P[B|A] = \\frac{P[A \\cap B]}{P[A]} = \\frac{P[B] \\times L[B|A]}{P[A]}$$\n\n- But really, we can think about it like this,\n\n$$\\text{posterior} = \\frac{\\text{prior} \\times \\text{likelihood}}{\\text{normalizing constant}}$$\n\n## **Homework**  \n\n- 1.3\n- 1.4\n- 1.8\n- 2.4\n- 2.9\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}